parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    # env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        default_connection:   pgsql
        connections:
            #Postgresql
            pgsql:
                driver:   pdo_pgsql
                host:     '%env(DATABASE_HOST)%'
                port:     '%env(DATABASE_PORT)%'
                dbname:   '%env(DATABASE_NAME)%'
                user:     '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                charset:  UTF8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            pgsql:
                connection: pgsql    # connection name for your additional DB
                # bundles utilisant la connexion Postgresql
                auto_mapping:         true
                mappings:
                   # PostgresqlBundle: ~
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        is_bundle: false
                        prefix: App\Entity
                        alias: App
