#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/homepage.html.twig
